/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.moblyft;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiProperties;

import android.app.Activity;

import com.moblyft.MoblyftSDK;
import com.moblyft.interfaces.MoblyftSDKListener;

@Kroll.module(name = "Moblyft", id = "ti.moblyft")
public class MoblyftModule extends KrollModule implements MoblyftSDKListener {
	// Standard Debugging variables
	public static final String LCAT = "Moblyft 💰💰";
	private Activity activity;
	private MoblyftSDK moblyft;
	private KrollFunction onResult;
	private KrollFunction onInit;
	private String MOBLYFT_APPKEY;
	private String MOBLYFT_USERID;
	MymoblyftAdListener lauscher = new MymoblyftAdListener();

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public MoblyftModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.d(LCAT, "inside onAppCreate");
	}

	@Kroll.method
	public void showAd(Object cb) {
		if (cb != null && cb instanceof KrollFunction) {
			onResult = (KrollFunction) cb;
			lauscher.setKroll(onResult, getKrollObject());
		}
		moblyft.showAd();
	}

	@Kroll.method
	public boolean isAdAvailable() {
		return moblyft.isAdAvailable();
	}

	@Kroll.method
	public void initSDK(KrollDict creds, KrollFunction onSuccess) {
		if (creds != null) {
			if (creds.containsKeyAndNotNull("appKey")) {
				MOBLYFT_APPKEY = creds.getString("appKey");
			}
			if (creds.containsKeyAndNotNull("userId")) {
				MOBLYFT_USERID = creds.getString("userId");
			}
		}
		if (onSuccess != null) {
			Object object = onSuccess;
			this.onInit = (KrollFunction) object;
		}
		moblyft.initSDKWithAppKey(activity, MOBLYFT_APPKEY, MOBLYFT_USERID);
		moblyft.setSDKListener(this);
		moblyft.setMoblyftAdListener(lauscher);

	}

	public void onStart(Activity activity) {
		this.activity = activity;
		TiProperties appProperties = TiApplication.getInstance()
				.getAppProperties();
		moblyft = new MoblyftSDK(activity);
		moblyft.initSDKWithAppKey(activity,
				appProperties.getString("MOBLYFT_APPKEY", ""),
				appProperties.getString("MOBLYFT_USERID", ""));

	}

	@Override
	public void moblyftInitSdkFailedWithError(String err) {
		if (onInit != null) {
			KrollDict res = new KrollDict();
			res.put("success", false);
			onInit.call(getKrollObject(), res);
		}
		Log.e(LCAT, "moblyftInitSdkFailedWithError=" + err);
	}

	@Override
	public void moblyftInitSdkSuccessful() {
		if (onInit != null) {
			KrollDict res = new KrollDict();
			res.put("success", true);
			onInit.call(getKrollObject(), res);
		}
		Log.d(LCAT, "moblyftInitSdkSuccessful");

	}
}
