/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.moblyft;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.TiProperties;

import android.app.Activity;

import com.moblyft.MoblyftSDK;
import com.moblyft.interfaces.MoblyftAdListener;
import com.moblyft.interfaces.MoblyftSDKListener;
import com.moblyft.pojo.MoblyftRewardInfo;

@Kroll.module(name = "Moblyft", id = "ti.moblyft")
public class MoblyftModule extends KrollModule implements MoblyftSDKListener {
	private final class moblyftAdListener implements MoblyftAdListener {
		@Override
		public void adAvailable() {
			Log.d(LCAT, "adAvailable");
		}

		@Override
		public void adFailedWithError(String errorMessage) {
			Log.d(LCAT, "adFailedWithError " + errorMessage);
			// This callback method will get call if ad is failed to cache
		}

		@Override
		public void adDidShow() {
			Log.d(LCAT, "adDidShow");
			// This callback method will get call when ad shows or get opened
		}

		@Override
		public void adDidHide() {
			// This callback method will get call when ad hides or get closed
		}

		@Override
		public void onRewardReceived(MoblyftRewardInfo rewardDetail) {
			// This callback method will only calls in case of Rewarded Video Ad
			// To get the reward details from 'rewardDetail' object
			String rewardName = rewardDetail.getRewardName();
			int rewardCount = rewardDetail.getRewardCount();
			Log.d(LCAT, "rewardName=" + rewardName);
		}
	}

	// Standard Debugging variables
	private static final String LCAT = "Moblyft 💰💰";
	private Activity activity;
	private MoblyftSDK moblyft;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public MoblyftModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.d(LCAT, "inside onAppCreate");
	}

	@Kroll.method
	public void showAd() {
		moblyft.showAd();
	}

	public void onStart(Activity activity) {
		this.activity = activity;
		TiProperties appProperties = TiApplication.getInstance()
				.getAppProperties();
		moblyft = new MoblyftSDK(activity);
		moblyft.initSDKWithAppKey(activity,
				appProperties.getString("MOBLYFT_APPKEY", ""),
				appProperties.getString("MOBLYFT_USERID", ""));
		moblyft.setSDKListener(this);
		moblyft.setMoblyftAdListener(new moblyftAdListener());
	}

	@Override
	public void moblyftInitSdkFailedWithError(String err) {
		Log.e(LCAT, "moblyftInitSdkFailedWithError=" + err);
	}

	@Override
	public void moblyftInitSdkSuccessful() {
		Log.d(LCAT, "moblyftInitSdkSuccessful");
	}
}
